### ISSUE TITLE
`make` fails

### ISSUE THREAD

**Issue by xloem** [stass/libsegfault#2]
surprised there's no issue around the makefile needing a specific local configuration.  does not build on linux for me:

```
[user@DESKTOP-E3P7TC0 libsegfault]$ make
Makefile:11: *** missing separator.  Stop.
```

**Comment by stass** [comment]
Hi xloem!  The Makefile in the project is for BSD make, not GNU Make. I can add a GMakefile for GNU make, but that still would not make it work on Linux most likely.  I'll see if I can get it going on Linux.

Just curious, what is the reason you'd like to use libsegfault on Linux instead of using one bundled with glibc?

**Comment by xloem** [comment]
I didn't know glibc already did this :-). Thanks, I'll try to remember that.
